# Generated by Django 2.2.23 on 2021-05-21 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=50, null=True)),
                ('producer', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('original_title', models.CharField(blank=True, max_length=100, null=True)),
                ('paginal_num', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('binding', models.CharField(blank=True, max_length=20, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_val', models.CharField(blank=True, max_length=5, null=True)),
                ('stars5', models.CharField(blank=True, max_length=5, null=True)),
                ('stars4', models.CharField(blank=True, max_length=5, null=True)),
                ('stars3', models.CharField(blank=True, max_length=5, null=True)),
                ('stars2', models.CharField(blank=True, max_length=5, null=True)),
                ('stars1', models.CharField(blank=True, max_length=5, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('translator', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('comment_type', models.IntegerField(choices=[(1, 'Movie'), (2, 'Book')], default=1)),
                ('dad_id', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('author_url', models.CharField(blank=True, max_length=200, null=True)),
                ('rating_val', models.CharField(blank=True, max_length=5, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=25, null=True)),
                ('imbd', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating_val', models.CharField(blank=True, max_length=5, null=True)),
                ('stars5', models.CharField(blank=True, max_length=5, null=True)),
                ('stars4', models.CharField(blank=True, max_length=5, null=True)),
                ('stars3', models.CharField(blank=True, max_length=5, null=True)),
                ('stars2', models.CharField(blank=True, max_length=5, null=True)),
                ('stars1', models.CharField(blank=True, max_length=5, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('actor', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
